import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-behavioral-health-parity-claims-audit",
  "engine": "recovery",
  "title": "Behavioral Health Parity Claims Audit",
  "shortTitle": "Behavioral Health Parity Claims Audit",
  "tagline": "Detect parity failures and quantify member, reimbursement, and regulatory exposure across quantitative and nonquantitative treatment limits.",
  "industry": "Health Plan Compliance",
  "buyer": "Health plans, employers, and behavioral-health administrators",
  "uiPort": 4650,
  "apiPort": 5650,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Behavioral Health Parity Claims Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence in one accountable workflow. Detect parity failures and quantify member, reimbursement, and regulatory exposure across quantitative and nonquantitative treatment limits.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Behavioral Health Parity Claims Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("plan-classification-mapping","BHP01","Plan classification mapping","Execute plan classification mapping using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed plan classification mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Plan classification mapping Reference","text","BHP01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("benefit-limit-comparison","BHP02","Benefit limit comparison","Execute benefit limit comparison using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed benefit limit comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Benefit limit comparison Reference","text","BHP02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("nqtl-inventory","BHP03","NQTL inventory","Execute nqtl inventory using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed nqtl inventory decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","NQTL inventory Reference","text","BHP03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("prior-authorization-comparison","BHP04","Prior authorization comparison","Execute prior authorization comparison using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed prior authorization comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Prior authorization comparison Reference","text","BHP04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("concurrent-review-comparison","BHP05","Concurrent review comparison","Execute concurrent review comparison using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed concurrent review comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Concurrent review comparison Reference","text","BHP05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("medical-necessity-criteria-review","BHP06","Medical necessity criteria review","Execute medical necessity criteria review using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed medical necessity criteria review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Medical necessity criteria review Reference","text","BHP06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("network-admission-analysis","BHP07","Network admission analysis","Execute network admission analysis using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed network admission analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Network admission analysis Reference","text","BHP07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("reimbursement-methodology-comparison","BHP08","Reimbursement methodology comparison","Execute reimbursement methodology comparison using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed reimbursement methodology comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Reimbursement methodology comparison Reference","text","BHP08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("denial-rate-analytics","BHP09","Denial rate analytics","Execute denial rate analytics using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed denial rate analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Denial rate analytics Reference","text","BHP09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("out-of-network-access-analysis","BHP10","Out-of-network access analysis","Execute out-of-network access analysis using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed out-of-network access analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Out-of-network access analysis Reference","text","BHP10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("comparative-analysis-workbench","BHP11","Comparative analysis workbench","Execute comparative analysis workbench using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed comparative analysis workbench decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Comparative analysis workbench Reference","text","BHP11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("member-impact-calculation","BHP12","Member impact calculation","Execute member impact calculation using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed member impact calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Member impact calculation Reference","text","BHP12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("corrective-action-workflow","BHP13","Corrective action workflow","Execute corrective action workflow using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed corrective action workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Corrective action workflow Reference","text","BHP13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("regulator-evidence-package","BHP14","Regulator evidence package","Execute regulator evidence package using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed regulator evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Regulator evidence package Reference","text","BHP14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]}),
feature("parity-governance-dashboard","BHP15","Parity governance dashboard","Execute parity governance dashboard using medical and behavioral benefits, NQTL policies, authorization data, network access, claims, denial rates, reimbursement, comparative analyses, and remediation evidence.","Produce a governed parity governance dashboard decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Benefit Classification","text","Plan / Benefit Classification · Standard Case"],["caseReference","Parity governance dashboard Reference","text","BHP15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",603750],["supportedAmount","Evidence-Supported Amount","currency",507150],["domainDriver","NQTL Category","select","Prior authorization",["Prior authorization","Network admission","Concurrent review"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan classification mapping case","Benefit limit comparison case","NQTL inventory case","Prior authorization comparison case","Concurrent review comparison case"]})
]);
